import React from "react";
import stylex from "@stylexjs/stylex";
import "./globals.css";
import testpage from "./test";

import test from "./test";
declare module 'react' {
  interface JSXIntrinsicElements {
    about: React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement>;
  }
}

const DARK_MODE = "@media (prefers-color-scheme: dark)";

// const s = stylex.create({
//   body: {
//     fontFamily: "sans-serif",
//     backgroundColor: {
//       default: "white",
//       [DARK_MODE]: "black",
//     },
//     color: {
//       default: "black",
//       [DARK_MODE]: "white",
//     },
//   },
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}

